spring.application.name=arl-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/arl_db
spring.datasource.username=postgres
spring.datasource.password=Arham@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080